apiVersion: apps/v1
kind: Deployment
metadata:
  name: program-service
  labels:
    app: program-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: program-service
  template:
    metadata:
      labels:
        app: program-service
    spec:
      containers:
        - name: program-service
          image: program-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://kertaskerja-postgres:5432/kertaskerja_program
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://kertaskerja-postgres:5432/kertaskerja_program
            - name: SPRING_PROFILES_ACTIVE
              value: testdata